### PR TITLE
Doc query

### PR DESCRIPTION
**Pull request by purplefox**
Extending Jamie's work on queries.

Various refactorings in this area and implementation of findMatching. Integration with the doc manager.

### CODE REVIEW

**Comment by purplefox** [comment]
@jcme Hi Jamie - any chance you could give this a once over?

Or @andyhedges  if Jamie is not available?

cheers!

**Comment by purplefox** [comment]
Also @jcme can you sign the CLA? Then we can get rid of that annoying message ;)

**Comment by jcme** [comment]
@purplefox This looks good to me. The new API for query results is much cleaner, with just the one class to worry about. The only thing we appear to have lost is the ability to provide the client the number of results, but I'm presuming the `isLast()` flag is intended as a substitute?

I've also signed the CLA with my public github username (jcme), but unfortunately a few commits creeped in from my work machine where Git was configured to use my work username. I can't sign the CLA with that username as it isn't a valid Public Github username, but I'll try to avoid commiting here with that username in the future!

**Comment by purplefox** [comment]
@jcme the trouble with number of results is not all storage engines will know how many results there are until they've all been iterated through, that's why I removed it.

**Pull request merged**
