### PR TITLE
Fridge

### PR DESCRIPTION
**Pull request by NigeWarren**
Possibly the most simple example using Events to update document state example using Fridge Status as the example context. 

Includes use of "Delivery" timestamps as an exploration of Delivery as well as Event objects.

### CODE REVIEW

**Comment by purplefox** [comment]
Thanks Nige will take a look shortly.

BTW, Can you sign the CLA? Only have to do this once

**Comment by NigeWarren** [comment]
Thanks Tim  -  I "signed electronically" the CLA looks like it has gone in to a further process of approval

**Comment by purplefox** [comment]
Looks good!

**Comment by purplefox** [comment]
Sometimes the CLA isn't marked as signed if you are using a different email address for GitHub than the one you used in the CLA...

**Pull request merged**
