### PR TITLE
Javadoc1

### PR DESCRIPTION
**Pull request by andyhedges**
Some initial javadoc comments

### CODE REVIEW

**Comment by purplefox** [comment]
Hi Andy, can you correct the conflicts?

**Comment by purplefox** [comment]
Andy, this PR seems to contain a lot of other stuff than javadoc

**Comment by andyhedges** [comment]
I rebased so it contains the changes on master since I made the branch, there is very little different between this and master though.

**Comment by purplefox** [comment]
ok fair enough, but normally i don't like to merge PRs that have been rebased like this as it's a nightmare to figure out what's actually changed and do a review, but in this case I guess it doesn't matter :)

**Comment by andyhedges** [comment]
`git diff master..javadoc1` will show you what's changed

**Pull request merged**
