### PR TITLE
Use QueryResult internally for findById

### PR DESCRIPTION
**Pull request by jcme**
- Uses `QueryResult` and `QueryResultHandler` internally for `findById`
- `expectedQueryResults` map now stores the `QueryResultHandler`, so queries with more than one result can be supported

I've also made quite a few interface changes, so feedback definitely appreciated.

In particular, I've renamed the old `QueryResult` to `QueryResultHandler` and the old `QueryResultHolder` to `QueryResult`. This is on the basis that the old `QueryResult` never actually contains the query results and isn't exposed to the consumer - it's only used internally. The old `QueryResultHolder` is what consumers will be presented with

### CODE REVIEW

**Comment by purplefox** [comment]
Hi Jamie,

I think you are on the right track with this.

I'm thinking it might make sense to rename QueryResultHandler to just QueryResponse and just have the numResults() method on it. - the handle() method is something that is called internally so I don't think it makes sense to expose it publicly.

QueryResult looks ok, but again I don't think we want to expose onAcknowledge publicly as this something just used internally.

**Comment by jcme** [comment]
@purplefox thanks for the review. Completely agree with you on hiding the two internal methods. I've added another commit with that changed.

**Comment by purplefox** [comment]
Hi Jamie, is the idea here to just get the find single document working before implementing findMatching?

**Comment by jcme** [comment]
Superceeded by #79

**Pull request closed without merging**
