### PR TITLE
Setupci

### PR DESCRIPTION
**Pull request by fbalicchia**
Here a basic setup configuration. For use this conf is necessary to enable to your account Travis CI, at the moment is possible to see this commit result here [result](https://travis-ci.org/fbalicchia/mewbase/builds/177220243)
IMHO in the near future is necessary to improve Travis configuration and pom layout adding some plugins, 
but i think this improvement need to follow the growth of the project

### CODE REVIEW

**Comment by purplefox** [comment]
Going back to the original question- is it not possible to configure Travis using a GitHub hook?

(I am a little confused here).

Also.. is that a key in the PR?

**Comment by fbalicchia** [comment]
As far as I know is possible to configure Travis community version to  trigger a build when there is a push or pull requests, this can be done from Travis web console.  Apologies,  but probably I struggle to understand a trivial thing that you want say to me

Yes, sorry that was my personal access tokens encrypted that is necessary to deploy on github from travis

**Comment by purplefox** [comment]
So basically, I haven't used Travis before, but I have used Jenkins before
on cloudbees.

Normally the way these things work is you first get an account with
Travis/cloudbees then you setup a GitHub hook on the project. The GitHub
hook is triggered on commit and tells the CI system to clone the project
and do a test run.

Usually you don't need to change anything in the project itself, so I am a
bit confused about what the changes in the PR are for.

Regarding your private key. Never add private keys to a public repository.
I suggest you change your key or others will be able to access your account.

HTH

On Sat, Nov 19, 2016 at 9:46 AM, filippo balicchia <notifications@github.com

**Comment by fbalicchia** [comment]
Hi,
I used Travis with my hobby projects not for professional 
but for configure it I follow  
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
https://docs.travis-ci.com/user/environment-variables/

Regarding my private key it not my private key but its my github token encrypt 
with travis command following 
https://blog.travis-ci.com/2013-01-28-token-token-token
http://blog.code4hire.com/2016/06/Adding-GitHub-token-to-Travis-CI-configuration/
https://docs.travis-ci.com/user/encryption-keys/

I close pull request and try to follow other way

**Pull request closed without merging**
