### PR TITLE
Set up continuous integration #50

### PR DESCRIPTION
**Pull request by fbalicchia**
Add travis configuration file for build and deploy artifact and uploading 
relese on github. to use it is necessary to change encrypt access tokens with yours. an align scm

Align to javaDoc to method firm for create realease

Add debian package I don't know if is ok for you  

add maven properties

### CODE REVIEW

**Comment by purplefox** [comment]
Hi Filippo,

Isn't it possible to set up integration with Travis just using a GitHub hook?

**Comment by fbalicchia** [comment]
Ok, I've remove all changes. travis file use only Github hook

**Comment by purplefox** [comment]
I assume this PR is unnecessary now?

Closing

**Comment by purplefox** [comment]
hi @fbalicchia did you manage to set up CI? might be a nice idea to mention on the google group if you did :)

**Pull request closed without merging**
