### PR TITLE
Changes for Issue 81

### PR DESCRIPTION
**Pull request by MyUmmaGumma**
Moves FileLogManagerOptions to ServerOptions.

### CODE REVIEW

**Comment by MyUmmaGumma** [comment]
The other hardcoded options in the code will be worked on separately as and when their presence is identified.

**Comment by purplefox** [comment]
Looks good. I think we need some tests for the options that you added in to ServerOptions, in OptionsTest.

Also, can you sign the CLA please? (See comment above)

**Comment by purplefox** [comment]
Hi @MyUmmaGumma how's it going with this?

**Comment by MyUmmaGumma** [comment]
Hi Tim,
Long weekend here in the US last week. I was off on vacation. Added the testcase - still having trouble signing the CLA despite adding my email address. (Figuring it out)

**Comment by purplefox** [comment]
Hey np!

Regarding the CLA - when this happens it's usually due to the email address you used to sign the CLA being different to the one you use in GitHub - they need to be the same.

Once that's fixed you'd also need to resubmit the PR as it won't recheck automatically.

**Comment by purplefox** [comment]
Closing this as superseded by other PR

**Pull request closed without merging**
