### PR TITLE
Add travis build #50

### PR DESCRIPTION
**Pull request by ssouris**
Travis is configured using a file called '.travis.yml' at the root of the repo. 
This file specifies the language in our case Java and the desired building and testing environment (maven build).
Travis needs to authorize to the projects' github account in order to work.
When a commit is pushed the build is triggered automatically. Also pull requests could be built like that.
Then depending on the build outcome developers can be notified (either via email , IRC, slack etc)

### CODE REVIEW

**Comment by ssouris** [comment]
Let me know what you think and basically what the minimum requirements for the CI are at the moment. So that I can be more accurate on the use of tooling. Thanks :)

**Comment by purplefox** [comment]
Basically we just want master branch on CI, and some kind of link from the project README to the CI page on travis.

**Comment by ssouris** [comment]
Ok now the script in the commit works as you mentioned.
- builds and runs test on master branch only
- has icon on README.md (Build Failed, Build Success) with link to the travis page

Another thing I forgot to mention is that the default notification settings say that an email is sent when:
- a build was just broken or still is broken
- a previously broken build was just fixed

**Comment by purplefox** [comment]
Thanks. When I go to link: https://travis-ci.org/Tesco/mewbase I get "This is not an active repository"

**Comment by ssouris** [comment]
You must sign in to travis-ci.org with github account and then go to 'Profile > Account' and enable the project. 
I can not do that since I do not have access to the github account of Tesco/mewbase.

**Comment by purplefox** [comment]
Thanks. It's up and running now.

**Pull request merged**
